name: Lint

on: push

jobs:
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Cache .npm
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-module-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-module-cache-
      - name: Cache node_modules and .cache
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
            ~/.cache
          key: ${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Lint workspace
        run: npm run lint
